#!/bin/bash
SCRIPTS_PATH="$( cd "$( dirname "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}") && pwd )"
#echo "SCRIPTS_PATH=$SCRIPTS_PATH"
export ROOT_HSR_REPO_PATH=$SCRIPTS_PATH/../..
#echo "ROOT_HSR_REPO_PATH=$ROOT_HSR_REPO_PATH"
MY_MODELS_PATH=$ROOT_HSR_REPO_PATH/src/world/model
#echo "MY_MODELS_PATH=$MY_MODELS_PATH"
source $ROOT_HSR_REPO_PATH/devel/setup.bash
export GAZEBO_MODEL_PATH=$MY_MODELS_PATH:$GAZEBO_REPO_PATH
#echo "GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH"





